// Auto-generates subtitles/captions for reels
// Uses LLM for translation into multiple languages
// Supports: en, ar, fr, it, and indigenous languages

export interface SubtitleTrack {
  language: string;
  captions: Array<{ start: number; end: number; text: string }>;
  isAutoGenerated: boolean;
}

// Generate subtitles from video description + audio transcript
export async function generateSubtitles(
  description: string,
  duration: number,
  sourceLanguage: string,
  targetLanguages: string[]
): Promise<SubtitleTrack[]> {
  const tracks: SubtitleTrack[] = [];
  
  // Generate source language captions (simulated segments)
  const sourceCaptions = generateSimulatedCaptions(description, duration);
  tracks.push({
    language: sourceLanguage,
    captions: sourceCaptions,
    isAutoGenerated: true,
  });

  // Translate to target languages
  for (const lang of targetLanguages) {
    if (lang === sourceLanguage) continue;
    const translated = await translateCaptions(sourceCaptions, sourceLanguage, lang);
    tracks.push({
      language: lang,
      captions: translated,
      isAutoGenerated: true,
    });
  }

  return tracks;
}

function generateSimulatedCaptions(text: string, duration: number): Array<{ start: number; end: number; text: string }> {
  const words = text.split(/\s+/);
  const wordsPerSegment = Math.max(3, Math.floor(words.length / Math.max(1, Math.floor(duration / 3))));
  const captions = [];
  const timePerWord = duration / words.length;

  for (let i = 0; i < words.length; i += wordsPerSegment) {
    const segment = words.slice(i, i + wordsPerSegment).join(' ');
    const start = i * timePerWord;
    const end = Math.min((i + wordsPerSegment) * timePerWord, duration);
    captions.push({ start: Math.round(start * 10) / 10, end: Math.round(end * 10) / 10, text: segment });
  }

  return captions;
}

async function translateCaptions(
  captions: Array<{ start: number; end: number; text: string }>,
  sourceLang: string,
  targetLang: string
): Promise<Array<{ start: number; end: number; text: string }>> {
  // In production: call LLM for translation
  // In dev: prefix text with language code
  return captions.map(c => ({
    ...c,
    text: `[${targetLang}] ${c.text}`,
  }));
}

// Format captions as VTT string for video player
export function captionsToVTT(track: SubtitleTrack): string {
  let vtt = 'WEBVTT\n\n';
  for (const c of track.captions) {
    const start = formatVTTTime(c.start);
    const end = formatVTTTime(c.end);
    vtt += `${start} --> ${end}\n${c.text}\n\n`;
  }
  return vtt;
}

function formatVTTTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toFixed(3).padStart(6, '0')}`;
}
